
zuul:
  routes:
    panda-auth: /auth/**
    panda-user-service: /admin/**
    panda-gen-service: /gen/**

ribbon:
  eager-load:
    enabled: true
    clients: panda-auth,panda-user-service

  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000

#关闭验证
management:
  metrics:
    web:
      server:
        auto-time-requests: false