eureka:
  client:
    service-url:
      defaultZone: http://193.112.100.103:8761/eureka/

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  datasource:
    url: "jdbc:mysql://${zipkin_mysql_host:127.0.0.1}:3306/cloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0