server:
  port: 9001
spring:
  datasource:
    url: "jdbc:mysql://${PANDA_USER_DB_HOST:172.31.18.86}:3306/cloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: "${PANDA_USER_DB_USER:root}"
    password: "${PANDA_USER_DB_PASSWD:root}"
    dbcp2:
      max-idle: 10
      min-idle: 5
      test-on-borrow: false
      time-between-eviction-runs-millis: 18800
      test-while-idle: true
      validation-query: SELECT 1
    hikari:
      minimum-idle: 0

  rabbitmq:
    host: 172.31.18.86
    port: 5672
    username: admin
    password: admin
    virtual-host: vhost

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://panda-server:8761/eureka/

